Ab/a30 new york times
selsa-inube/bootcamp-apr pull request #225
Opened 2024-05-14 20:47 UTC by Angelbt12

completed work

2024-06-03 16:54 UTC, carin91 requested changes

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: 6.5%;
Group lines 12 and 14 in 1 line.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: 6.5%;
Why do you use this exotic value? 6.5%...

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: -120px;
You are looking to occupies more space than the tag. Why do you need this?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-top: 51%;
It looks like you are placing elements with its margins instead of the properties of the container. You must place elements based on the container over any other why. Is this container a display=flex? in this case you must use its properties to place its children

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    font-size: 15px;
This will apply to every p which is a descendant of a nav. I guess you are just thinking in your specific case and not thinking in a page. How do you guarantee that this will apply just for the date in the nav you want?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +nav p:nth-child(1){
This will apply to every p which is a descendant of a nav. I guess you are just thinking in your specific case and not thinking in a page.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-right: 20px;
Avoid direct assignations to the margin for locating elements. Use the properties for the different containers.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: -25%;
If you have a relative position, why do you use margin-left instead of left?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    border: 1px solid black;
You are assigning this prop for both buttons and then deleting it?, this is more work for the compiler.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +nav  a:hover{
There is pending to include the underline for the pseudo-class hover
![image](https://github.com/selsa-inube/bootcamp-apr/assets/123512032/cba315ff-88a2-4157-920a-39790a896d76)

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    padding: 30px;
i would use a minor value for the padding, considering the reference image. You must define props to look as exactly as possible to the reference.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    cursor: pointer;
You could avoid this prop considering the line 124.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin: 0 2%;
is this like "try and catch"? You are defining values verifying what will happen to the page instead of considering the mocks? why do you use a margin in percentage?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    padding-bottom: 2%;
is this like "try and catch"? You are defining values verifying what will happen to the page instead of considering the mocks? why do you use a margin in percentage?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-top: 2%;
is this like "try and catch"? You are defining values verifying what will happen to the page instead of considering the mocks? why do you use a margin in percentage?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-top: 3%;
is this like "try and catch"? You are defining values verifying what will happen to the page instead of considering the mocks? why do you use a margin in percentage?

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +article:nth-child(2) > div > div:first-child:after{
This selector is very confusing. Every time you read this code you will need to remember the exact location of every article and so on. What happens if the editor in chief decide to reorder things? => you will need to redefine all of the styles. You must simplify the style sheet using classes, id's and so on.

2024-06-03 16:54 UTC, carin91 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +            <p>Thursday</p>
Adjust the styles for this paragraph to complete the word, in this moment it lacks the last "y".

2024-06-04 12:44 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +        <h1>The New Hork Times</h1>
I couldn't find the same font and the one that most resembles it is paid

2024-06-04 12:53 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +            <li><a href="#">Magnize</a></li>
ok I'll fix it

2024-06-04 12:54 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    padding-bottom: 2%;
ok I'll fix it

2024-06-04 12:56 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-top: 2%;
ok I'll fix it

2024-06-04 19:11 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +    <nav>
I separated it since it makes me more organized and I can adjust my styles more easily, I will take into account the observations and fix my code

2024-06-04 19:12 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +article:nth-child(2) > div > div:first-child:after{
I will take into account the observations and fix my code

2024-06-05 18:24 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +            <p>May 21,2020</p>
Sorry, I didn't understand this comment correctly.

2024-06-06 14:44 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <button>TECM FIX</button>
OK

2024-06-06 15:02 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <div>
ok

2024-06-06 15:08 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <h5>Everything You Need to Know About Slow Internet Speeds</h5>
ok

2024-06-06 15:18 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <button>Continue Reading</button>
I thought they were buttons

2024-06-06 15:29 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <button>Continue Reading</button>
ok

2024-06-06 15:30 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                    <div></div>
ok

2024-06-06 15:34 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <h2>A Wave of Small Business Closures Is on the Way. Can Washington Stop It?</h2>
sorry, I fixed my mistake

2024-06-06 16:00 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                    <p>May 19, 2020</p>
ok

2024-06-06 16:02 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <div>
ok

2024-06-06 16:06 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                        <p>Another Grim Tally of U.S. Unemployement Is Exoected: Live Business Updates</p>
If you are right, you already make the changes

2024-06-06 16:08 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                    <div>
ok

2024-06-06 16:09 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <h3>Fast Foward</h3>
ok

2024-06-06 16:15 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                    <img src="img/fast1.png" alt="">
ok

2024-06-06 16:25 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.html
> +                <p>6:07 AM</p>
ok

2024-06-06 16:27 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: 6.5%;
ok

2024-06-06 16:35 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: -120px;
I do it because it is so I can leave the sidebar on the left side completely

2024-06-06 16:41 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    font-size: 15px;
ok

2024-06-06 16:45 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +nav p:nth-child(1){
ok, I already made the changes, because if it is wrong

2024-06-06 16:45 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    font-size: 15px;
ok, I already made the changes, because if it is wrong

2024-06-06 16:47 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-right: 20px;
ok

2024-06-06 16:49 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    margin-left: -25%;
ok

2024-06-06 18:06 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +nav  a:hover{
ok

2024-06-06 18:09 UTC, Angelbt12 commented on src/ab/html/A2-Markup-a-readme/A30-New-York-Times/A30-New-York-Times.css
> +    padding: 30px;
ok

2024-06-12 10:46 UTC, merged