l2-program-structure.md
selsa-inube/bootcamp-apr pull request #236
Opened 2024-05-20 14:50 UTC by Angelbt12

finished exercises

2024-05-22 21:12 UTC, carin91 requested changes

2024-05-22 21:12 UTC, carin91 commented on src/ab/js/l2/Chessboard.js
> +no;
is it a mistake?

2024-05-23 13:02 UTC, Angelbt12 commented on src/ab/js/l2/Chessboard.js
> +no;
Yes, it's a mistake, I've fixed it now.

2024-06-03 17:23 UTC, carin91 approved these changes

2024-06-03 17:23 UTC, merged