L3: functions
selsa-inube/bootcamp-apr pull request #238
Opened 2024-05-20 16:15 UTC by Brandonz07

2024-05-22 21:32 UTC, carin91 requested changes

2024-05-22 21:32 UTC, carin91 commented on src/br/js/L3-functions/BeanCounting.js
> +function countChar(a, b) {
It is recommended to use names for the variables that could be understandable by everyone. Change The names for all of the arguments of the components.

2024-05-22 21:32 UTC, carin91 commented on src/br/js/L3-functions/BeanCounting.js
> +function countBs(a) {
It is recommended to use names for the variables that could be understandable by everyone. Change The names for all of the arguments of the components.

2024-05-22 21:32 UTC, carin91 commented on src/br/js/L3-functions/BeanCounting.js
> +
There is pending 1 activity: Rewrite countBs to make use of this new function.

2024-05-22 21:32 UTC, carin91 commented on src/br/js/L3-functions/Minimum.js
> +  } else if (a > b) {
avoid unnecessary calculations.

2024-05-27 22:01 UTC, Brandonz07 commented on src/br/js/L3-functions/BeanCounting.js
> +function countChar(a, b) {
change variable names

2024-05-27 22:01 UTC, Brandonz07 commented on src/br/js/L3-functions/BeanCounting.js
> +function countBs(a) {
change variable names

2024-05-27 22:01 UTC, Brandonz07 commented on src/br/js/L3-functions/BeanCounting.js
> +
I rewrote counBs

2024-05-27 22:03 UTC, Brandonz07 commented on src/br/js/L3-functions/Minimum.js
> +  } else if (a > b) {
use a ternary operator

2024-06-03 17:25 UTC, carin91 approved these changes

2024-06-03 17:25 UTC, merged