L4-data-structures
selsa-inube/bootcamp-apr pull request #240
Opened 2024-05-20 16:56 UTC by Angelbt12

finished exercises

2024-06-03 18:14 UTC, carin91 requested changes

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/A-ist.js
> +  for (let i = array.length - 1; i >= 0; i--) {
refactor using i++

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/A-ist.js
> +  for (let node = list; node; node = node.rest) {
avoid the coercion

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/A-ist.js
> +  else return nth(list.rest, index - 1);
refactor to a non-recursive function

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/Deep-comparison.js
> +      if (!keysB.includes(key) || !deepEqual(a[key], b[key])) {
refactor with the and operator

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/Reversing-an-array.js
> +  for (let i = array.length - 1; i >= 0; i--) {
refactor with i++

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/Reversing-an-array.js
> +  for (let i = 0; i < Math.floor(array.length / 2); i++) {
refactor using i--

2024-06-03 18:14 UTC, carin91 commented on src/ab/js/l4/The-sum-of-a-range.js
> +  } else {
refactor to avoid the else statement

2024-06-04 20:59 UTC, Angelbt12 commented on src/ab/js/l4/A-ist.js
> +  for (let i = array.length - 1; i >= 0; i--) {
ok

2024-06-04 20:59 UTC, Angelbt12 commented on src/ab/js/l4/A-ist.js
> +  for (let node = list; node; node = node.rest) {
ok

2024-06-04 20:59 UTC, Angelbt12 commented on src/ab/js/l4/A-ist.js
> +  else return nth(list.rest, index - 1);
ok

2024-06-04 20:59 UTC, Angelbt12 commented on src/ab/js/l4/Deep-comparison.js
> +      if (!keysB.includes(key) || !deepEqual(a[key], b[key])) {
ok

2024-06-04 20:59 UTC, Angelbt12 commented on src/ab/js/l4/Reversing-an-array.js
> +  for (let i = array.length - 1; i >= 0; i--) {
ok

2024-06-04 21:00 UTC, Angelbt12 commented on src/ab/js/l4/The-sum-of-a-range.js
> +  } else {
ok

2024-06-06 23:24 UTC, carin91 approved these changes

2024-06-06 23:24 UTC, merged