L5-higher-order-functions
selsa-inube/bootcamp-apr pull request #241
Opened 2024-05-20 21:09 UTC by Angelbt12

finished activities

2024-06-03 18:22 UTC, carin91 requested changes

2024-06-03 18:22 UTC, carin91 commented on src/ab/js/l5/Your-own-loop.js
> +  while (test(value)) {
refactor it using recursion

2024-06-04 22:08 UTC, Angelbt12 commented on src/ab/js/l5/Your-own-loop.js
> +  while (test(value)) {
ok

2024-06-06 23:25 UTC, carin91 approved these changes

2024-06-06 23:25 UTC, merged