L6-the-secret-life-of-objects
selsa-inube/bootcamp-apr pull request #242
Opened 2024-05-21 15:18 UTC by Angelbt12

finished exercises

2024-06-03 18:46 UTC, carin91 requested changes

2024-06-03 18:46 UTC, carin91 commented on src/ab/js/l6/Groups.js
> +      const index = this.members.indexOf(value);
refactor using the has method

2024-06-04 22:14 UTC, Angelbt12 commented on src/ab/js/l6/Groups.js
> +      const index = this.members.indexOf(value);
ok

2024-06-06 23:34 UTC, carin91 approved these changes

2024-06-06 23:34 UTC, merged