L4: data structures
selsa-inube/bootcamp-apr pull request #243
Opened 2024-05-27 00:57 UTC by Brandonz07

2024-06-03 18:06 UTC, carin91 requested changes

2024-06-03 18:06 UTC, carin91 commented on src/br/js/L4-data-structures/The_sum_of_a_range.js
> +  let sum = 0;
refactor using reduce method for arrays.

2024-06-06 18:40 UTC, Brandonz07 commented on src/br/js/L4-data-structures/The_sum_of_a_range.js
> +  let sum = 0;
i use reduce

2024-06-06 18:42 UTC, Brandonz07 commented on src/br/js/L4-data-structures/A_list.js
> +  for (let node = list; node; node = node.resto) {
avoid use

2024-06-06 18:42 UTC, Brandonz07 commented on src/br/js/L4-data-structures/A_list.js
> +function nth(list, n) {
avoid use

2024-06-06 18:43 UTC, Brandonz07 commented on src/br/js/L4-data-structures/Deep_comparison.js
> +    return a === b;
to compare simple values

2024-06-06 23:18 UTC, carin91 approved these changes

2024-06-06 23:18 UTC, merged