Ab/l7 project a robot
selsa-inube/bootcamp-apr pull request #257
Opened 2024-05-27 17:46 UTC by Angelbt12

robot project

2024-06-03 19:08 UTC, carin91 requested changes

2024-06-03 19:08 UTC, carin91 commented on src/ab/js/l7/l7-project-a-robot.js
> +    route = routes.reduce((a, b) =>
Define more descriptive names.

2024-06-07 12:35 UTC, Angelbt12 commented on src/ab/js/l7/l7-project-a-robot.js
> +    if (state.parcels.length == 0) {
ok

2024-06-07 12:35 UTC, Angelbt12 commented on src/ab/js/l7/l7-project-a-robot.js
> +    route = routes.reduce((a, b) =>
ok

2024-06-12 12:17 UTC, carin91 approved these changes

2024-06-12 12:17 UTC, merged