L5: higher order functions
selsa-inube/bootcamp-apr pull request #258
Opened 2024-05-27 19:37 UTC by Brandonz07

2024-06-03 18:29 UTC, carin91 requested changes

2024-06-03 18:29 UTC, carin91 commented on src/br/js/L5-higher-order-functions/Dominant_writing_direction.js
> +        let known = counts.findIndex(c => c.name == name);
use a more descriptive name instead of "c"

2024-06-03 18:29 UTC, carin91 commented on src/br/js/L5-higher-order-functions/Everything.js
> +    return array.every(element => test(element));
refactor to avoid the use of the every method in array

2024-06-03 18:29 UTC, carin91 commented on src/br/js/L5-higher-order-functions/Flattening.js
> +console.log(arrays.reduce((accumulator, current) => accumulator.concat(current), []));
refactor to define a function which flatten the array.

2024-06-03 18:29 UTC, carin91 commented on src/br/js/L5-higher-order-functions/Your_own_loop.js
> +    while (test(value)) {
refactor to avoid the use of while

2024-06-06 16:23 UTC, Brandonz07 commented on src/br/js/L5-higher-order-functions/Dominant_writing_direction.js
> +        let known = counts.findIndex(c => c.name == name);
I changed the name

2024-06-06 16:23 UTC, Brandonz07 commented on src/br/js/L5-higher-order-functions/Everything.js
> +    return array.every(element => test(element));
i no use every

2024-06-06 16:23 UTC, Brandonz07 commented on src/br/js/L5-higher-order-functions/Flattening.js
> +console.log(arrays.reduce((accumulator, current) => accumulator.concat(current), []));
create the function

2024-06-06 16:23 UTC, Brandonz07 commented on src/br/js/L5-higher-order-functions/Your_own_loop.js
> +    while (test(value)) {
i use for

2024-06-06 23:32 UTC, carin91 approved these changes

2024-06-06 23:32 UTC, merged