L7: project a robot
selsa-inube/bootcamp-apr pull request #260
Opened 2024-05-28 19:56 UTC by Brandonz07

2024-06-03 19:12 UTC, carin91 requested changes

2024-06-03 19:12 UTC, carin91 commented on src/br/js/L7-project-a-robot/Persistent_group.js
> +        return new PGroup(this.members.filter(v => v !== value));
use a more descriptive name for v

2024-06-03 19:12 UTC, carin91 commented on src/br/js/L7-project-a-robot/Persistent_group.js
> +        return new PGroup(this.members.filter(v => v !== value));
create a new static method from and refactor this line with it.

2024-06-06 19:18 UTC, Brandonz07 commented on src/br/js/L7-project-a-robot/Persistent_group.js
> +        return new PGroup(this.members.filter(v => v !== value));
i changed name

2024-06-11 03:26 UTC, Brandonz07 commented on src/br/js/L7-project-a-robot/Persistent_group.js
> +        return new PGroup(this.members.filter(v => v !== value));
static method

2024-06-12 12:17 UTC, carin91 approved these changes

2024-06-12 12:17 UTC, merged