A30: New york times
selsa-inube/bootcamp-apr pull request #267
Opened 2024-06-05 00:15 UTC by Brandonz07

2024-06-06 23:09 UTC, carin91 requested changes

2024-06-06 23:09 UTC, carin91 commented on src/br/html/A30-New-York-Times/styles/style.css
> +article:first-child h2{
you have a class; however, you are styling based on the pseudoelement. I would delete the class define for this one.

2024-06-06 23:09 UTC, carin91 commented on src/br/html/A30-New-York-Times/styles/style.css
> +.point:after{
I don't get it. Are you defining a div to render it's after pseudo element? I would condition the div to look like a point or something else, there are too many html nodes without use.

2024-06-06 23:09 UTC, carin91 commented on src/br/html/A30-New-York-Times/styles/style.css
> +.foward p:last-child{
It is better to define a better html tag for the first paragraph, considering it as a heading.

2024-06-08 04:11 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/A30-New-York-Times.html
> +            <p>May 21, 2020</p>
changed tag

2024-06-08 04:12 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/A30-New-York-Times.html
> +                    <button class="continue">Continue Reading</button>
changed tag a

2024-06-08 04:13 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/A30-New-York-Times.html
> +                <div class="news">
very similar styles

2024-06-08 04:13 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/A30-New-York-Times.html
> +                <div id="ponts">
delete id

2024-06-08 04:13 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/A30-New-York-Times.html
> +                <div class="foward">
changed name

2024-06-08 04:13 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/A30-New-York-Times.html
> +                        <p>Another Grim Tally of U.S. Unemployement Is Exoected: Live Business Updates</p>
i use h3

2024-06-08 04:14 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    margin-left: -6.5%;
I don't use negatives anymore

2024-06-08 04:15 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    width: 3%;
i use fixed-size units

2024-06-08 04:16 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    display: flex;
no

2024-06-08 04:16 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +ul:first-child > li > a > i{
changed selectors

2024-06-08 04:16 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    margin-left: -25%;
i use left

2024-06-08 04:17 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    border: 1px solid black;
add a hover

2024-06-08 04:18 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    text-decoration: none;
add a underline

2024-06-08 04:18 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +    color: rgb(167, 166, 166);
changed font and color

2024-06-08 04:19 UTC, Brandonz07 commented on src/br/html/A30-New-York-Times/styles/style.css
> +.point:after{
don't use pseudo elements

2024-06-08 04:21 UTC, Brandonz07 commented
I used grid instead of flex, add the nav to the header, change the section to main, and in the last column use float

2024-06-12 10:40 UTC, carin91 approved these changes

2024-06-12 10:40 UTC, merged